apiVersion: apps/v1
kind: Deployment
metadata:
   name: connecteduimgl1-deployment
spec:
   replicas: 1
   selector:
     matchLabels:
        app: connecteduimgl1
   template:
      metadata:
          name: connectedu-pod
          labels: 
             app: connecteduimgl1
      spec:
         containers:
             - name: connecteduimgl1
               image: dockerkabap/connecteduimgl1:latest
               ports:
                 - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: connecteduimgl1-svc
spec:
   selector:
      app: connectedu-app-srv
   type: NodePort
   ports:
      - port: 3000
        targetPort: 80
        nodePort: 30000
