--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: connecteduimgl1-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: connecteduimgl1
  template: 
    metadata: 
      labels: 
        app: connecteduimgl1
    spec: 
      containers: 
        - image: "dockerkabap/connecteduimgl1:latest"
          name: connecteduimgl1
          ports: 
            - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
   name: voting-app-svc
   spec:
      selector:
         app: vote
      type: NodePort
      ports:
         - port: 3000
           targetPort: 80
           nodePort: 30000
