apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb-app-pod
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-app-container
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-app-svc
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opeque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=
